extraction:
  # Define settings for C# analysis
  csharp:
    # The `index` step builds the code and extracts information during the build
    # process.
    index:
      solution: "Twidsty.Engine/Twidsty.Engine.csproj"
      # Specify MSBuild settings.
      dotnet:
        # Specify the MSBuild configuration to use, for example, debug or release.
        # Default: read from the solution file or files.
        arguments: "-c GitHub"
