namespace Twisty.Engine.Structure.Builders;

/// <summary>
/// Enum describing the type for RotationCoreFormat.
/// </summary>
public enum RotationCoreFormatEntryType
{
	None,
	Load,
	Union
}

/// <summary>
/// Interface allowing to define a format entry for a RotationCore.
/// </summary>
/// <typeparam name="T">Type of the values provided by this IRotationCoreFormatEntry instance.</typeparam>
public interface IRotationCoreFormatEntry<T>
{
	/// <summary>
	///	Type identifier that will allow to know the uniquely identify the format type.
	/// </summary>
	RotationCoreFormatEntryType Type { get; }

	/// <summary>
	/// Gets the Values generated by this Format Entry.
	/// </summary>
	/// <param name="context">The context used to load data from the storage.</param>
	/// <returns></returns>
	IEnumerable<T> GetValues(RotationCoreBuilderContext context);
}
