name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Setup SonarSource
      run: dotnet tool install --global dotnet-sonarscanner --version 4.7.1
    - name: Prepare SonarCube Analysis
      run: dotnet sonarscanner begin /k:"jardons_twisty-engine" /o:"jardons"  /d:sonar.host.url=https://sonarcloud.io /d:"sonar.login=${{ secrets.SONAR_TOKEN }}"
    - name: Build with dotnet
      run: dotnet build
    - name: Publish to SonarSource
      run: dotnet sonarscanner end /d:"sonar.login=${{ secrets.SONAR_TOKEN }}"
    - name: Run Units Tests
      run: dotnet test

  sonarCloudTrigger:
    needs: build
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
